In [1]:
import numpy as np

**Error handling**

>1․ Եթե որպես ֆունկցիայի պարամետր ստանում եք numpy զանգված (վեկտոր կամ մատրից), և այն չի համապատասխանում խնդրում նշված չափին (dimensions) կամ չափերի անհամաձայնություններ կան, ապա վերադարցրեք (return) **"DimensionError"** տեքստը

>2․ Եթե որպես ֆունկցիայի պարամետր ստանում եք 2D numpy զանգված (մատրից), և այն հակադարձելի (invertable) չէ, հակառակ խնդրի պահանջի, ապա վերադարցրեք(return) **"NotInvertableError"** տեքստը

# Problems

#### Problem 1.

Հաշվիր 2 զանգվածների Էվկլիդյան հեռավորությունը։

```
a, b = np.array([1, 2]), np.array([1, 3])
print(dist(a, b))
>>>1
```

In [74]:
import numpy as np
def dist(a, b):
    
    return np.linalg.norm(a - b)

In [10]:
# Do not modify this cell
a, b = np.array([1, 1]), np.array([1, 3])
assert dist(a, b) == 2

a, b = np.array([-10, 1.5]), np.array([0.9, 3.6])
assert round(dist(a, b), 2) == 11.1

a, b = np.array([1, 1, 1]), np.array([0, -1, 3])
assert dist(a, b) == 3

a, b = np.array([1, 0, -999]), np.array([1, 3])
assert dist(a, b) == "DimensionError"

a, b = np.array([10, -1, 9, 1, 2.98, -0.14]), np.array([0, -1, 3.14, np.pi, 99, np.e])
assert round(dist(a, b), 2) == 96.78

#### Problem 2.

Նորմավորիր զանգվածը այնպես, որ արժեքները լինեն 0-ից 1 միջակայքում։

```
a = np.array([1,2,3,4])
print(rescale(a))
>>[0, 0.3333333, 0.66666667, 1]
```

In [11]:
import numpy as np
def rescale(a):
    min = np.min(a)
    max = np.max(a)
    norm = (a-min) / (max-min)
    return norm


array([0.        , 0.33333333, 0.66666667, 1.        ])

In [8]:
# Do not modify this cell
assert np.all(rescale(np.array([1, 2, 3, 4])) == [0, 1/3, 2/3, 1])
assert np.all(rescale(np.array([0, 1])) == [0, 1])
assert np.all(rescale(np.array([0, 10])) == [0, 1])
assert np.all(rescale(np.array([1, 2, 4])) == [0, 1/3, 1])

#### Problem 3.

Տրված է numpy զանգված 'a', որը պարունակում է n էլեմենտ, b-ով նշանակենք նրա ունիկալ արժեքների (արժեքներն առանց կրկնության) զանգվածը ըստ աճման կարգի, m-ով նշանակենք b զանգվածի չափը: Հարկավոր է ստեղծել numpy զանգված $n \times m$ չափերով, որի i-րդ տողի j-րդ սյան տեղում պետք է գրված լինի 1 այն դեպքում, երբ a-ի i-րդ անդամը հավասար է b֊ի j-րդ արժեքին, իսկ մնացած տեղերում պետք է լինեն 0֊ներ։

```
a = np.array([1, 1, 2, 3, 2, 4])
# b = np.array([1, 2, 3, 4])
print(convert(a))
>>[[1, 0, 0, 0],
  [1, 0, 0, 0],
  [0, 1, 0, 0],
  [0, 0, 1, 0],
  [0, 1, 0, 0],
  [0, 0, 0, 1]]
```

In [15]:
import numpy as np
def convert(a):
    b = np.unique(a)
    result = (a[:, None] == b)
    
    return result


In [16]:
# Do not modify this cell
assert np.all(convert(np.array([0, 0, 2, 3, 2, 4])) ==
              [[1, 0, 0, 0],
               [1, 0, 0, 0],
               [0, 1, 0, 0],
               [0, 0, 1, 0],
               [0, 1, 0, 0],
               [0, 0, 0, 1]])

assert np.all(convert(np.array([-np.pi, 9])) ==
              [[1, 0],
               [0, 1]])

assert np.all(convert(np.array([-1, 1, 9, 10])) ==
              [[1, 0, 0, 0],
               [0, 1, 0, 0],
               [0, 0, 1, 0],
               [0, 0, 0, 1]])

assert np.all(convert(np.array([np.sqrt(2), np.sqrt(2), np.sqrt(2)])) ==
              [[1],
               [1],
               [1]])

#### Problem 4.

Տրված է 2D numpy զանգված 'a' $n \times m$ չափերի, Հարկավոր է կողքերից հավասարաչափ 0-ներ ավելացնել այնպես, որ զանգվածի չափերը դառնան $(n+2n_1) \times (m+2m_1)$

```
a = np.array([[1, 1], [1, 1]])
n1 = 1
m1 = 2
print(padding(a, n1, m1))
>>[[0, 0, 0, 0, 0, 0], 
  [0, 0, 1, 1, 0, 0],
  [0, 0, 1, 1, 0, 0],
  [0, 0, 0, 0, 0, 0]]
```

In [37]:
import numpy as np

def padding(a, n1, m1):
    pad_widths = [[n1]*2, [m1]*2]
    
    return np.pad(a, pad_widths)

In [38]:
# Do not modify this cell
assert np.all(padding(np.array([[1, 1], [1, 1]]), 1, 2) ==
              [[0, 0, 0, 0, 0, 0],
               [0, 0, 1, 1, 0, 0],
               [0, 0, 1, 1, 0, 0],
               [0, 0, 0, 0, 0, 0]])

assert np.all(padding(np.array([[1, 2], [1, 1]]), 0, 2) ==
              [[0, 0, 1, 2, 0, 0],
               [0, 0, 1, 1, 0, 0]])

assert np.all(padding(np.array([[9]]), 2, 2) ==
              [[0, 0, 0, 0, 0],
               [0, 0, 0, 0, 0],
               [0, 0, 9, 0, 0],
               [0, 0, 0, 0, 0],
               [0, 0, 0, 0, 0]])

#### Problem 5.

Տրված է 2D numpy զանգվածներ 'a' և 'b' համապատասխանաբար $m \times n$ և $k \times k$ չափերի (k<=n, k<=m), 2 ամբողջ թվեր 'stride' և 'padding' ու 'f' ֆունկցիա։ Հարկավոր է
- 'a' մատրիցին 'padding' չափով 0֊ներ ավելացնել յուրաքանչյուր կողմից,
- ապա 'b'֊ն 'stride' քայլով "շարժել" 'a'֊ի վրայով և 'a'֊ի համապատասխան էլեմենտները բազմապատկել 'b'-ի համապատասխան էլեմենտներով,
- ստացված k*k հատ թվերը գումարել,
- արդյունքի վրա կիրառել 'f' ֆունկցիան
- և տեղադրել նոր մատրիցում։

```
a = np.array([[1, 1, 2],
              [0, 1, 3],
              [1, 3, 0],
              [4, 5, 2]])
b = np.array([[1, 0],
              [0, 1]])

stride = 1
padding = 0
f = lambda x: x**2
print(conv(a, b, stride, padding, f))
>>[[4, 16],
  [9, 1],
  [36, 25]]
```
![ConvUrl](https://miro.medium.com/max/2340/1*Fw-ehcNBR9byHtho-Rxbtw.gif "conv")

In [82]:
def conv(a,b, stride,padding, f):
    if padding:
        a= np.pad(e,padding)
    ah,aw = a.shape
    bh, bw =b. shape
    if bh != bw:
        return "DimensionError"
    res = np.zeros((ah-bh+1 )// stride, (aw-bw+1)// stride)
    rh,rw = res.shape
    for i in range(rh):
        for j in range(rw):
            res[i,j] = f(np.sum(a[i* stride:i*stride +bh ,j * stride:j * stride +bw] *b))
    return res

In [ ]:
# Do not modify this cell
a = np.array([[1, 1, 2],
              [0, 1, 3],
              [1, 3, 0]])
b = np.array([[1, 0],
              [0, 1]])
f = lambda x: x**2
assert np.all(conv(a, b, 1, 0, f) ==
              [[4., 16.],
               [9.,  1.]])

a = np.array([[1, 1, 2],
              [0, 1, 3],
              [1, 3, 0],
              [-10, -3, 0]])
b = np.arange(9).reshape(3, 3)
f = lambda x:0 if x<0 else x
assert np.all(conv(a, b, 1, 0, f) ==
              [[51.],
               [0.]])

b = np.arange(6).reshape(2, 3)
assert conv(a, b, 1, 0, f) == "DimensionError"

#### Problem 6.

Տրված է 2D numpy զանգված 'a' $m \times n$ չափերի, որն ունի բացակայող էլեմենտներ (NAN) ու տեքստային փոփոխական 'mode' $\in$ {"mean","min","max"}։ Հարկավոր է 'a' մատրիցի բացակայող էլեմենտների փոխարեն գրել համապատասխան սյան {միջինը, մինիմումը, մաքսիմումը} ըստ 'mode' փոփոխականի։

```
a = np.array([[np.nan, 200, 10],
              [2, 110, np.nan],
              [0, 120, 11],
              [0, 400, np.nan],
              [1, np.nan, 9]])
mode = "mean"
print(fill(a, mode))
>>>[[  0.75 200.    10.  ]
    [  2.   110.    10.  ]
    [  0.   120.    11.  ]
    [  0.   400.    10.  ]
    [  1.   207.5    9.  ]]
```

In [21]:
import numpy as np
def fill(a, mode):
    new = a.copy()
    if mode == "mean":
        res = np.nanmean(a,axis=0)
    elif mode == "min":
        res = np.nanmin(a,axis=0)
    elif mode == "max":
        res = np.nanmax(a,axis=0)
    i = np.where(np.isnan(a))
    new[i] = res[i[1]]
    return new



In [23]:
# Do not modify this cell
a = np.array([[np.nan, 200, 10],
              [2, 110, np.nan],
              [0, 120, 11],
              [0, 400, np.nan],
              [1, np.nan, 9]])

assert np.all(fill(a, "mean") ==
              [[0.75, 200.,  10.],
               [2., 110.,  10.],
               [0., 120.,  11.],
               [0., 400.,  10.],
               [1., 207.5,   9.]])

assert np.all(fill(a, "min") ==
              [[0., 200.,  10.],
               [2., 110.,   9.],
               [0., 120.,  11.],
               [0., 400.,   9.],
               [1., 110.,   9.]])

assert np.all(fill(a, "max") ==
              [[2., 200.,  10.],
               [2., 110.,  11.],
               [0., 120.,  11.],
               [0., 400.,  11.],
               [1., 400.,   9.]])

#### Problem 7.

Տրված է numpy մատրից 'A' $n \times n$ չափերի և numpy վեկտոր 'b' n չափի։ Հարկավոր է հաշվել հետևյալ արտահայտության արժեքը։
$${1\over2}\mathbf{b}^TA^{-1}\mathbf{b}*\prod_{i}\lambda_i ; \text{ որտեղ $\lambda_i$֊երը A-ի սեփական արժեքներն են}$$

```
a = np.array([[1, 1, 2],
              [0, 1, 3],
              [1, 3, 0]])
b = np.array([1, 0, 1])
print(calc(a, b))
>>>-4.000000000000002
```


In [33]:
def calc(a, b):
    if a.shape[0] != b.shape[0]:
        return "DimensionError"
    det = np.linalg.det(a)
        
    if det == 0:
        return "NotInvertableError"
    inv = np.linalg.inv(a)
    r = b.T @ inv @ b
    res = 0.5 * r *det
    return res

In [34]:
# Do not modify this cell
a = np.array([[1, 1, 2],
              [0, 1, 3],
              [1, 3, 0]])
b = np.array([1, 0, 1])
assert round(calc(a, b)) == -4

a = np.array([[1, 1, 2],
              [0, 1, 3],
              [1, 3, 0]])
b = np.array([1, 0, 1, 1])
assert calc(a, b) == "DimensionError"

a = np.array([[1, 1, 2],
              [1, 1, 3],
              [3, 3, 0]])
b = np.array([1, 0, 1])
assert calc(a, b) == "NotInvertableError"

a = np.array([[10, 1],
              [-1, 1]])
b = np.array([1, 1])
assert round(calc(a, b), 2) == 5.5

#### Problem 8.

Տրված է $m \times n$ չափերի numpy մատրից 'a'։ Հարկավոր է գտնել 'a'-ի այն տողերը՝ որոնց էլեմենտների գումարը գտնվում է [100,200) միջակայքում։

```
a = np.array([[1, 1, 2],
              [0, 108, 3],
              [1, 3, 65],
              [50, 35, 5],
              [5, 83, 110],
              [98, 99, 10],
              [8, 9, 103],
              [9, 23, 15]])
print(between_100_200(a))
>>>[[0, 108, 3],
    [5, 83, 110],
    [8, 9, 103]]
```

In [45]:
def between_100_200(a):
    suma = np.sum(a,axis=1)
    return a[(suma >=100) & (suma <200)]



[[  0 108   3]
 [  5  83 110]
 [  8   9 103]]


In [46]:
# Do not modify this cell
a = np.array([[1, 1, 2],
              [0, 108, 3],
              [1, 3, 65],
              [50, 35, 5],
              [5, 83, 110],
              [98, 99, 10],
              [8, 9, 103],
              [9, 23, 15]])
assert np.all(between_100_200(a) ==
              [[0, 108,   3],
               [5,  83, 110],
               [8,   9, 103]])

a = np.array([[1, 1, 2],
              [0, -108, 3],
              [1, 3, 65],
              [50, 35, 5]])
assert len(between_100_200(a)) == 0

#### Problem 9.

Գրել ֆունկցիա, որը կվերադարձնի տրված չափանի երկչափ numpy array (քառակուսի մատրից), շախմատի տախտակի նման։  

In [48]:
def chess(dim):
    res = np.zeros((dim, dim))
    

    res[::2, ::2] = 1
    res[1::2, 1::2] =1
    return res


array([[1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.]])

In [49]:
assert np.array_equal(chess(4), np.array([
    [1., 0., 1., 0.,],
    [0., 1., 0., 1.,],
    [1., 0., 1., 0.,],
    [0., 1., 0., 1.,]
]))

assert np.array_equal(chess(8), np.array([
    [1., 0., 1., 0., 1., 0., 1., 0.],
    [0., 1., 0., 1., 0., 1., 0., 1.],
    [1., 0., 1., 0., 1., 0., 1., 0.],
    [0., 1., 0., 1., 0., 1., 0., 1.],
    [1., 0., 1., 0., 1., 0., 1., 0.],
    [0., 1., 0., 1., 0., 1., 0., 1.],
    [1., 0., 1., 0., 1., 0., 1., 0.],
    [0., 1., 0., 1., 0., 1., 0., 1.]
]))

#### Problem 10. 

Գրել ֆունկցիա, որը կվերադարձնի տրված չափանի երկչափ numpy array (քառակուսի մատրից), որտեղ եզրերում կլինեն 1-եր, իսկ ներսում՝ 0-ներ։  

In [62]:
def zero_one(x):
    res = np.ones((x,x))
    res[1:-1,1:-1] = 0
    return res
# zero_one(4)


array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

In [63]:
assert np.array_equal(zero_one(3), np.array([[1., 1., 1.],
                                            [1., 0., 1.],
                                            [1., 1., 1.]]))
assert np.array_equal(zero_one(4), np.array([[1., 1., 1., 1],
                                            [1., 0., 0., 1],
                                            [1., 0., 0., 1],
                                            [1., 1., 1., 1]]))